# Generated by Django 5.1.1 on 2024-10-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_alter_client_table_alter_employee_table_and_more'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;"),
    ]
